# Generated by Django 3.2.3 on 2021-06-30 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name="heure et date de l'evenement ")),
                ('heure_debut', models.DateTimeField(null=True, verbose_name="date et heure de debut de l' evenement")),
                ('lieu', models.TextField(verbose_name="lieu de l'agape")),
                ('fichier', models.FileField(blank=True, null=True, upload_to='', verbose_name="photos ou videos de l' evenements")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Culte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name="heure et date de l'evenement ")),
                ('theme', models.CharField(max_length=200)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='', verbose_name="photos ou videos de l' evenements")),
                ('moderateur', models.CharField(max_length=50)),
                ('predicateur', models.CharField(blank=True, max_length=50, null=True)),
                ('resume_predication', models.TextField(verbose_name='resume de la predication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name="heure et date de l'evenement ")),
                ('theme', models.CharField(max_length=200)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='', verbose_name="photos ou videos de l' evenements")),
                ('corp_enseignement', models.TextField(verbose_name="corp de l' enseignement")),
                ('enseignant', models.CharField(max_length=50, verbose_name="nom de l'enseignant")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name="heure et date de l'evenement ")),
                ('theme', models.CharField(max_length=200)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='', verbose_name="photos ou videos de l' evenements")),
                ('moderateur', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Priere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name="heure et date de l'evenement ")),
                ('theme', models.CharField(max_length=200)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='', verbose_name="photos ou videos de l' evenements")),
                ('moderateur', models.CharField(max_length=50)),
                ('exhortation', models.CharField(blank=True, max_length=50, null=True, verbose_name="personne en charge de l'exhoration")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Evenement',
        ),
        migrations.CreateModel(
            name='CulteSpecial',
            fields=[
                ('culte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evenements.culte')),
                ('predicateur2', models.CharField(blank=True, max_length=50, null=True, verbose_name='deuxième predicateur')),
                ('service_prophetique', models.CharField(blank=True, max_length=50, null=True, verbose_name='service prophetique')),
                ('service_prophetique2', models.CharField(blank=True, max_length=50, null=True, verbose_name='deuxieme intervenant aux service prophetique')),
            ],
            options={
                'abstract': False,
            },
            bases=('evenements.culte',),
        ),
    ]
