# Generated by Django 3.2.3 on 2021-07-01 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0002_auto_20210630_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agape',
            name='heure_debut',
        ),
    ]
