# Generated by Django 3.2.3 on 2021-06-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name="heure et date de l'evenement ")),
                ('type', models.CharField(choices=[('agape', 'agape'), ('culte', 'culte'), ('culte special', 'culte special'), ('enseignement', 'enseignement'), ('prière', 'prière'), ('partage', 'partage')], default='culte', help_text="le type de l'evenement", max_length=100)),
                ('adresseC', models.TextField(help_text=' Lubumbashi/C. kenya/Av. circulaire/n°303')),
            ],
        ),
    ]
