# Generated by Django 3.2.3 on 2021-07-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0003_remove_agape_heure_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culte',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='photos_evenements', verbose_name="photos ou videos de l' evenements"),
        ),
        migrations.AlterField(
            model_name='culte',
            name='moderateur',
            field=models.CharField(choices=[('daniel sadiki', 'daniel sadiki')], default='Auncun', max_length=70),
        ),
        migrations.AlterField(
            model_name='culte',
            name='predicateur',
            field=models.CharField(blank=True, choices=[('daniel sadiki', 'daniel sadiki')], default='Auncun', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='enseignement',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='photos_evenements', verbose_name="photos ou videos de l' evenements"),
        ),
        migrations.AlterField(
            model_name='partage',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='photos_evenements', verbose_name="photos ou videos de l' evenements"),
        ),
        migrations.AlterField(
            model_name='partage',
            name='moderateur',
            field=models.CharField(choices=[('daniel sadiki', 'daniel sadiki')], default='Auncun', max_length=70),
        ),
        migrations.AlterField(
            model_name='priere',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='photos_evenements', verbose_name="photos ou videos de l' evenements"),
        ),
        migrations.AlterField(
            model_name='priere',
            name='moderateur',
            field=models.CharField(choices=[('daniel sadiki', 'daniel sadiki')], default='Auncun', max_length=70),
        ),
    ]
